### ISSUE TITLE
Unable to load schema from path/to/manifest.json

### ISSUE THREAD

**Issue by SleeplessByte** [expo/vscode-expo#164]
### Description of the bug

Recently `app.json` has no longer been able to load the manifest. This is also on a fresh machine that never had the extension, so I am certain it's not due to cache poisoning.

### To Reproduce
What steps did you perform which led to this issue?

1. Install the extension
2. npx create-react-app
3. open `app.json`

#### Expected behavior

There are no warnings or errors

#### Actual behavior

```
Unable to load schema from 'c:\Users\Derk-Jan\AppData\Roaming\Code\User\globalStorage\bycedric.vscode-expo\manifest-43.0.0.json': 
ENOENT: no such file or directory, open 'c:\Users\Derk-Jan\AppData\Roaming\Code\User\globalStorage\bycedric.vscode-expo\manifest-43.0.0.json'.(768)
```

### Additional context

I'm on windows, which could have been deducted from the file path.

There is no folder `bycedric.vscode-expo` inside `c:\Users\Derk-Jan\AppData\Roaming\Code\User\globalStorage`, or anywhere else in the filetree.

**Comment by byCedric** [comment]
Hi @SleeplessByte! Could it be possible that your `settings.json` still has deprecated `json.schemas` settings for Expo? If so, please remove that manually. 

I tried to migrate everyone over since [`0.8.0`](https://github.com/expo/vscode-expo/commit/2d567acbbfac69abd304b7ad37bb1d26b846d5c6#diff-5d670efd1adde9e086878f976b2a3a7f9e704a9aa470fc6b38b600d4e46b8021) (_see issue #83 for more info_, but all code related to the "legacy method" of adding the XDL schema has been removed since [`0.8.1`](https://github.com/expo/vscode-expo/commit/5b4d675dc8b4d097b4471ea9ee3182c081a767ba) _released ±1.5 months later_.

**Comment by SleeplessByte** [comment]
@byCedric Yes, that's definitely possible as I sync settings.

After removing it manually from the `settings` the problem goes away. 

My recommendation would be to document this in the README.md at a minimum. For future changes like this, you may want to offer a migration option, or explicitly remove the value from people their settings. This is possible by passing `undefined` to the `update` command, although I don't know what the correct syntax would be for changing an array.
